In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/youtube/youtube.csv",index_col=0)
df.head()

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01

## 1. 인기동영상 제작횟수가 많은 채널 상위 10개명을 출력하라 (날짜기준, 중복포함)

In [19]:
list(df.pivot_table(index = 'channelTitle', values = 'title', aggfunc = 'count').sort_values(by ='title',ascending = False).head(10).reset_index()['channelTitle'])

['짤툰',
 '파뿌리',
 'SPOTV',
 '런닝맨 - 스브스 공식 채널',
 '엠뚜루마뚜루 : MBC 공식 종합 채널',
 '장삐쭈',
 'BANGTANTV',
 '채널 십오야',
 '이과장',
 '총몇명']

## 2. 논란으로 인기동영상이 된 케이스를 확인하고 싶다. dislikes수가 like 수보다 높은 동영상을 제작한 채널을 모두 출력하라

In [26]:
cond2 = df['likes'] < df['dislikes']
df2 = df.loc[cond2]
list(df2['channelTitle'].unique())

['핫도그TV',
 'ASMR 애정TV',
 '하얀트리HayanTree',
 '양팡 YangPang',
 '철구형 (CHULTUBE)',
 '왜냐맨하우스',
 '(MUTUBE)와꾸대장봉준',
 '오메킴TV',
 '육지담',
 'MapleStory_KR',
 'ROAD FIGHTING CHAMPIONSHIP',
 '사나이 김기훈',
 '나혼자산다 STUDIO',
 'Gen.G esports']

## 3. 채널명을 바꾼 케이스가 있는지 확인하고 싶다. channelId의 경우 고유값이므로 이를 통해 채널명을 한번이라도 바꾼 채널의 갯수를 구하여라

In [40]:
df3 = df.pivot_table(index = 'channelId', values = 'channelTitle', aggfunc = 'nunique').reset_index()
cond3 = df3['channelTitle'] == 1
answer = len(df3.loc[~cond3])
answer

71

##  4. 일요일에 인기있었던 영상들 중 가장많은 영상 종류(categoryId)는 무엇인가?

In [57]:
df['trending_date2_dt'] = pd.to_datetime(df['trending_date2'])
df['요일'] = df['trending_date2_dt'] .dt.day_name()
df['요일'].unique()

array(['Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday',
       'Thursday'], dtype=object)

In [70]:
cond4 = df['요일'] == 'Sunday'
df4 = df.loc[cond4]
df4['categoryId'].value_counts().sort_values(ascending = False).index[0]

24

## 5. 각 요일별 인기 영상들의 categoryId는 각각 몇개 씩인지 하나의 데이터 프레임으로 표현하라

In [75]:
answer = pd.DataFrame(df.pivot_table(index = 'categoryId', columns = '요일', values = 'title', aggfunc ='count'))
answer

요일          Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
categoryId
1              243     263       255     274       246      257        234
2              120     105       119      99       128      119        129
10             833     837       776     830       890      894        917
15             187     215       198     217       207      208        207
17             633     668       592     636       682      708        706
19              90      92        87      91        92       89         85
20             283     298       296     289       282      285        291
22            1288    1373      1289    1337      1341     1375       1333
23             568     594       570     556       560      569        566
24            2976    3148      3066    3096      2954     3084       3090
25             444     453       422     437       470      452        468
26             369     378       364     363       375      394        385
27             183     205       183     199       194      194        212
28             171     160       173     167       166      161        165
29              12      10        10       9        13       11         12

## 6.댓글의 수로 (comment_count) 영상 반응에 대한 판단을 할 수 있다. 
## viewcount대비 댓글수가 가장 높은 영상을 확인하라 (view_count값이 0인 경우는 제외한다)

In [81]:
cond6 = df['view_count'] !=0 
df6 = df.loc[cond6]

In [84]:

df6['시청자대비댓글수'] = df6['comment_count'] / df6['view_count']
df6

C:\Users\campus2H058\AppData\Local\Temp\ipykernel_18520\5796722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['시청자대비댓글수'] = df6['comment_count'] / df6['view_count']

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2,trending_date2_dt,요일,시청자대비댓글수
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01,2021-01-01,Friday,0.004539
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01,2021-01-01,Friday,0.007739
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01,2021-01-01,Friday,0.000513
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01,2021-01-01,Friday,0.006566
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01,2021-01-01,Friday,0.006349
...,...,...,...,...,...,...,...,...,...,...,...,...
60394,*풀코스로 먹습니다* 🍗치킨 + 🍕피자 + 🥧디저트,공룡,22,538190,16671,209,3117,UCWf4QKgnTyvmehcRqw-JldQ,2021-10-19,2021-10-19,Tuesday,0.005792
60395,[놀면 뭐하니? 예고] 우린 깐부잖아🦑 놀뭐에 등장한 월드클래스 초대손님!! MBC...,놀면 뭐하니?,24,1607562,14615,258,1141,UCx6jsZ02B4K3SECUrkgPyzg,2021-10-19,2021-10-19,Tuesday,0.000710
60396,먹방 전쟁 : 사랑스러War (feat. 401 정육식당),김종국 GYM JONG KOOK,17,1125911,26490,263,1915,UCoe-0EVDJnjlSoPK8ygcGwQ,2021-10-19,2021-10-19,Tuesday,0.001701
60397,＂너.. 광수지?＂ 협상에 거짓말부터 던지는 광수 닮은꼴 김연경 선수 [런닝맨|21...,스브스 예능맛집,24,1741773,14994,304,802,UCnx4Fi4cmkLGDiFfZ311wWw,2021-10-19,2021-10-19,Tuesday,0.000460
60398,ENHYPEN (엔하이픈) 'Tamed-Dashed' Official MV,HYBE LABELS,10,13753485,1784532,9737,195461,UC3IZKseVpdzPSBaWxBxundA,2021-10-19,2021-10-19,Tuesday,0.014212

In [101]:
list(df6.sort_values(by ='시청자대비댓글수', ascending = False).head(1)['title'])[0]

'60분 동안 댓글이 달리지 않으면, 영상이 삭제됩니다. (챌린지)'

## 7. 댓글의 수로 (comment_count) 영상 반응에 대한 판단을 할 수 있다.viewcount대비 댓글수가 가장 낮은 영상을 확인하라 (view_counts, ratio값이 0인경우는 제외한다.)

In [104]:

df7 = df6.loc[df6['시청자대비댓글수'] !=0 ]
list(df7.sort_values(by ='시청자대비댓글수').head(1)['title'])[0]

'Join the BTS #PermissiontoDance Challenge only on YouTube #Shorts'

## 8. like 대비 dislike의 수가 가장 적은 영상은 무엇인가? (like, dislike 값이 0인경우는 제외한다)

In [108]:
df

,title,channelTitle,categoryId,view_count,likes,dislikes,comment_count,channelId,trending_date2,trending_date2_dt,요일
0,[신병] 물자창고,장삐쭈,23,1893473,38249,730,8595,UChbE5OZQ6dRHECsX0tEPEZQ,2021-01-01,2021-01-01,Friday
1,RAIN(비) - 나로 바꾸자 Switch to me (duet with JYP) MV,RAIN's Official Channel,10,2600864,0,0,20129,UCxXgIeE5hxWxHG6dz9Scg2w,2021-01-01,2021-01-01,Friday
2,2020년 제야의 종 온라인 타종행사 | 보신각 현장 행사는 진행하지 않습니다.,서울시 · Seoul,29,347049,3564,120,178,UCZUPZW5idAxYp-Asj__lVAA,2021-01-01,2021-01-01,Friday
3,고기남자의 칠면조 파티,고기남자 MeatMan,26,528458,15372,280,3470,UCT3CumbFIJiW33uq0UI3zlg,2021-01-01,2021-01-01,Friday
4,골목 3mc를 분노하게 만든 마음고생이 심했을 공릉 백반집 사장님의 푸념?! [예능...,스브스밥집,24,494904,3918,111,3142,UCdWgRSfttvDucq4ApcCg5Mw,2021-01-01,2021-01-01,Friday
...,...,...,...,...,...,...,...,...,...,...,...
60394,*풀코스로 먹습니다* 🍗치킨 + 🍕피자 + 🥧디저트,공룡,22,538190,16671,209,3117,UCWf4QKgnTyvmehcRqw-JldQ,2021-10-19,2021-10-19,Tuesday
60395,[놀면 뭐하니? 예고] 우린 깐부잖아🦑 놀뭐에 등장한 월드클래스 초대손님!! MBC...,놀면 뭐하니?,24,1607562,14615,258,1141,UCx6jsZ02B4K3SECUrkgPyzg,2021-10-19,2021-10-19,Tuesday
60396,먹방 전쟁 : 사랑스러War (feat. 401 정육식당),김종국 GYM JONG KOOK,17,1125911,26490,263,1915,UCoe-0EVDJnjlSoPK8ygcGwQ,2021-10-19,2021-10-19,Tuesday
60397,＂너.. 광수지?＂ 협상에 거짓말부터 던지는 광수 닮은꼴 김연경 선수 [런닝맨|21...,스브스 예능맛집,24,1741773,14994,304,802,UCnx4Fi4cmkLGDiFfZ311wWw,2021-10-19,2021-10-19,Tuesday
60398,ENHYPEN (엔하이픈) 'Tamed-Dashed' Official MV,HYBE LABELS,10,13753485,1784532,9737,195461,UC3IZKseVpdzPSBaWxBxundA,2021-10-19,2021-10-19,Tuesday

In [114]:
cond81 = df['likes'] != 0
cond82 = df['dislikes'] != 0
df8 = df.loc[cond81 | cond82]

In [123]:
df8['like_ratio'] = df8['dislikes'] / df8['likes']
list(df8.sort_values(by = 'like_ratio').head(1)['title'])[0]

C:\Users\campus2H058\AppData\Local\Temp\ipykernel_18520\4270089851.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df8['like_ratio'] = df8['dislikes'] / df8['likes']

"국힙 래퍼 데프콘의 자존심을 건 불꽃 튀는 상품 판매! Let's go bebe 🚀 [쓔퍼맨] EP.3 대학로지구 #EVENT"

## 9. 가장많은 트렌드 영상을 제작한 채널의 이름은 무엇인가? (날짜기준, 중복포함)

In [135]:
list(pd.DataFrame(df['channelTitle'].value_counts()).reset_index().sort_values(by = 'count', ascending = False).head(1)['channelTitle'])[0]

'짤툰'

## 10. 20회(20일)이상 인기동영상 리스트에 포함된 동영상의 숫자는?

In [148]:
df10 = pd.DataFrame(df[['title','channelTitle']].value_counts()).reset_index()
answer = len(df10.loc[df10['count'] >= 20 ])
answer

40

In [147]:
answer= (df[['title','channelId']].value_counts()>=20).sum()
print(answer)

40